import React, { useContext } from 'react';
import { AuthContext } from '../App';

const TermsPage = () => {
  const { language } = useContext(AuthContext);

  return (
    <div style={{ backgroundColor: '#000000', color: '#D4AF37', minHeight: '100vh', padding: '2rem' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '3rem', paddingTop: '2rem' }}>
          <h1 className={language === 'ar' ? 'arabic-text' : ''} style={{
            fontSize: 'clamp(2rem, 4vw, 3rem)',
            fontWeight: '700',
            fontFamily: 'Playfair Display, serif',
            marginBottom: '1rem',
            textShadow: '0 0 15px rgba(212, 175, 55, 0.5)'
          }}>
            {language === 'ar' ? 'شروط الاستخدام' : 'Terms of Use'}
          </h1>
          <p style={{ fontSize: '0.9rem', opacity: 0.8 }}>
            {language === 'ar' ? 'آخر تحديث: أغسطس 2025' : 'Last Updated: August 2025'}
          </p>
        </div>

        {/* Terms Sections */}
        {[
          {
            title: { ar: 'الاستخدام المصرّح به', en: 'Authorized Use' },
            content: { ar: 'المنصة تخدم أغراض التحليل المالي فقط، ويُحظر استخدامها لأغراض غير قانونية أو مشبوهة أو لإنشاء خدمات منافسة.', en: 'The platform serves financial analysis purposes only, and it is prohibited to use it for illegal or suspicious purposes or to create competing services.' }
          },
          {
            title: { ar: 'الملكية الفكرية', en: 'Intellectual Property' },
            content: { ar: 'جميع حقوق النظم، الكود، المحتوى، التصميم، والتحليلات مملوكة حصريًا لـ FinClick.AI ولا يحق للمستخدم إعادة توزيع أو بيع المخرجات كمحتوى آلي.', en: 'All rights to systems, code, content, design, and analyses are exclusively owned by FinClick.AI and users may not redistribute or sell outputs as automated content.' }
          },
          {
            title: { ar: 'الدقة والمسؤولية', en: 'Accuracy and Responsibility' },
            content: { ar: 'بالرغم من دقتنا العالية، لا نتحمل أي مسؤولية قانونية عن أي قرارات مالية تتخذها بناءً على التحليل المولد من النظام.', en: 'Despite our high accuracy, we do not bear any legal responsibility for any financial decisions you make based on the analysis generated by the system.' }
          },
          {
            title: { ar: 'الاشتراك', en: 'Subscription' },
            content: { ar: 'أي تأخير في الدفع يوقف الحساب تلقائيًا. ولا يحق للمستخدم مشاركة الحساب مع غيره. اشتراك واحد = مستخدم واحد فقط.', en: 'Any delay in payment automatically suspends the account. Users may not share accounts with others. One subscription = one user only.' }
          },
          {
            title: { ar: 'إنهاء الاستخدام', en: 'Termination of Use' },
            content: { ar: 'يحق لـ FinClick.AI إيقاف أو تعطيل أي حساب يستخدم المنصة بشكل مسيء أو غير قانوني.', en: 'FinClick.AI reserves the right to suspend or disable any account that uses the platform in an abusive or illegal manner.' }
          },
          {
            title: { ar: 'تعديل الشروط', en: 'Terms Modification' },
            content: { ar: 'تحتفظ إدارة المنصة بحق تعديل هذه الشروط في أي وقت، ويتم إشعارك عبر البريد الإلكتروني.', en: 'The platform management reserves the right to modify these terms at any time, and you will be notified via email.' }
          }
        ].map((section, index) => (
          <section key={index} style={{ marginBottom: '3rem', padding: '2rem', backgroundColor: 'rgba(212, 175, 55, 0.1)', borderRadius: '15px', border: '1px solid rgba(212, 175, 55, 0.3)' }}>
            <h2 className={language === 'ar' ? 'arabic-text' : ''} style={{
              fontSize: '1.8rem',
              fontWeight: '600',
              fontFamily: 'Playfair Display, serif',
              marginBottom: '1.5rem',
              color: '#D4AF37'
            }}>
              {language === 'ar' ? section.title.ar : section.title.en}
            </h2>
            <p className={language === 'ar' ? 'arabic-text' : ''} style={{
              fontSize: '1.1rem',
              lineHeight: '1.8',
              textAlign: language === 'ar' ? 'right' : 'left'
            }}>
              {language === 'ar' ? section.content.ar : section.content.en}
            </p>
          </section>
        ))}

        {/* Back Button */}
        <div style={{ textAlign: 'center', marginTop: '3rem' }}>
          <button 
            onClick={() => window.history.back()}
            style={{
              backgroundColor: '#D4AF37',
              color: '#000',
              border: 'none',
              padding: '1rem 2rem',
              borderRadius: '8px',
              fontSize: '1rem',
              fontWeight: '600',
              cursor: 'pointer',
              transition: 'all 0.3s ease'
            }}
          >
            {language === 'ar' ? 'العودة للصفحة الرئيسية' : 'Back to Home'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;